export const GET_QURAN_CHAPTERS = 'GET_QURAN_CHAPTERS';
export const GET_CHAPTER_VERSES = 'GET_CHAPTER_VERSES';
export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';